"use client";

import FooterComponent from "@/app/component/FooterComponent/FooterComponent";
import { Plus_Jakarta_Sans } from "next/font/google";
import MainNavBar from "../component/Navbar/mainNavBar";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const jakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"] ,
  weight: ['400', '500', '700'], 
  variable: '--font-plus-jakarta', 
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <div
        className={`${jakarta.className}`}
      >
        <MainNavBar />
        
        {children}
      

        <main className="flex-grow  bg-[#ffffff] pt-10 pb-10">
          <FooterComponent />
          <div className="text-center text-sm mt-4  border-gray-600 ">
            <a
              href="https://cozaktechnologies.in"
              className="flex items-center justify-center gap-2"
            >
              https://cozaktechnologies.in
            </a>
          </div>
        </main>
      </div>
   
  );
}
