"use client";
import InnerHeaderBanner from "@/app/component/BannerComponents/InnerPageBanner";
import FooterComponent from "@/app/component/FooterComponent/FooterComponent";
import Partners from "@/app/component/PartnerComponent/Partner";
import MainNavBar from "@/app/component/Navbar/mainNavBar";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get current path
  const slug = pathname.split("/").filter(Boolean).pop();

  const getHeaderTitle = () => {
    if (slug === "mobile_development") {
      return "MOBILE APP DEVELOPMENT";
    } else if (slug === "seo") {
      return "SEARCH ENGINE OPTIMIZATION";
    } else if (slug === "web_development") {
      return "WEB DEVELOPMENT";
    } else if (slug === "web_design") {
      return "WEB DESIGNING";
    } else {
      return "";
    }
  };

  return (
    <main className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <MainNavBar />
      <section className="flex-grow bg-[#013E57] pt-16">
        <InnerHeaderBanner title={getHeaderTitle()} bannerKey={slug} />
      </section>
      {children}
      <section className="flex-grow  bg-[#FFFFFF] pt-0 pb-10">
        <Partners />
      </section>

      <section className="flex-grow  bg-[#ffffff] pt-10 pb-10">
        <FooterComponent />
        <div className="text-center text-sm mt-4  border-gray-600 ">
          <a
            href="https://cozaktechnologies.in"
            className="flex items-center justify-center gap-2"
          >
            https://cozaktechnologies.in
          </a>
        </div>
      </section>
    </main>
  );
}
